"""Core package for the data analysis agent learning project."""

from .analysis import load_sales, profit_by_month, profit_by_product, summarize_sales
from .agent import (
    DEFAULT_MODEL,
    MAX_QUESTION_LENGTH,
    AgentToolStep,
    DataAgentOutput,
    DataAgentRun,
    ask_data_agent,
    create_data_agent,
    run_data_agent,
)
from .charts import save_monthly_profit_chart
from .insights import (
    build_analysis_report,
    find_risk_orders,
    generate_business_insights,
    monthly_performance,
    performance_by_dimension,
)
from .report_workflow import (
    AnalysisPlan,
    AnalysisReport,
    AnalysisWorkflowRun,
    ReportFinding,
    analysis_report_to_markdown,
    available_analysis_sections,
    collect_analysis_evidence,
    run_analysis_workflow,
)
from .rag import (
    EMBEDDING_MODEL,
    KnowledgeChunk,
    KnowledgeHit,
    KnowledgeIndex,
    build_knowledge_index,
    load_knowledge_chunks,
    load_knowledge_index,
    retrieve_business_knowledge,
    search_knowledge,
)

__all__ = [
    "DEFAULT_MODEL",
    "EMBEDDING_MODEL",
    "MAX_QUESTION_LENGTH",
    "AgentToolStep",
    "AnalysisPlan",
    "AnalysisReport",
    "AnalysisWorkflowRun",
    "DataAgentOutput",
    "DataAgentRun",
    "KnowledgeChunk",
    "KnowledgeHit",
    "KnowledgeIndex",
    "ReportFinding",
    "analysis_report_to_markdown",
    "ask_data_agent",
    "available_analysis_sections",
    "build_analysis_report",
    "build_knowledge_index",
    "create_data_agent",
    "collect_analysis_evidence",
    "find_risk_orders",
    "generate_business_insights",
    "load_sales",
    "load_knowledge_chunks",
    "load_knowledge_index",
    "monthly_performance",
    "performance_by_dimension",
    "profit_by_month",
    "profit_by_product",
    "save_monthly_profit_chart",
    "summarize_sales",
    "run_data_agent",
    "run_analysis_workflow",
    "retrieve_business_knowledge",
    "search_knowledge",
]
